version: '3'
services:
    php:
        image: php:7.4.3-apache-buster
        volumes:
            - ./docker/conf.conf:/etc/apache2/sites-enabled/000-default.conf
            - ./php/:/app/php/
        environment:
            APACHE_DOCUMENT_ROOT: /app/php
            docker: "true"
        working_dir: /app/php
        ports:
            - "6001:80"

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: 'laravel'
            MYSQL_USER: 'admin'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - "3001:3306"

